const initialCars = [
    {
        id: 1,
        model: "Toyota Corolla",
        driverId: 1,
        kilometers: 12000,
        lastUpdated: "2024-01-06",
        licensePlate: "ABC123",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: "2024-01-01",
        dailyUsage: 0,
        estMaintainance: null,
    },
    {
        id: 2,
        model: "Honda Civic",
        driverId: 2,
        kilometers: 15000,
        lastUpdated: "2025-01-05",
        licensePlate: "DEF456",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: "2024-01-01",
        dailyUsage: 0,
        estMaintainance: null,
    },
    {
        id: 3,
        model: "Ford Focus",
        driverId: 3,
        kilometers: 8000,
        lastUpdated: "2025-01-04",
        licensePlate: "GHI789",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: null,
        dailyUsage: 0,
        estMaintainance: null,
    },
    {
        id: 4,
        model: "Chevrolet Cruze",
        driverId: 4,
        kilometers: 20000,
        lastUpdated: "2025-01-03",
        licensePlate: "JKL012",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: null,
        dailyUsage: 0,
        estMaintainance: null,
    },
];

module.exports = initialCars;

