const initialCars = [
    {
        id: 1,
        model: "Toyota Corolla",
        driverId: 1,
        kilometers: 12000,
        lastUpdated: "2024-01-06",
        licensePlate: "ABC123",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: "2024-01-01",
        dailyUsage: 0,
        estMaintainance: null,
        address: {
            street: "123 Main St",
            city: "Springfield",
            latitude: 38.89511,
            longitude: -77.03637
        },
    },
    {
        id: 2,
        model: "Honda Civic",
        driverId: 2,
        kilometers: 15000,
        lastUpdated: "2025-01-05",
        licensePlate: "DEF456",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: "2024-01-01",
        dailyUsage: 0,
        estMaintainance: null,
        address: {
            street: "456 Elm St",
            city: "Springfield",
            latitude: 38.89511,
            longitude: -77.03637
        },
    },
    {
        id: 3,
        model: "Ford Focus",
        driverId: 3,
        kilometers: 8000,
        lastUpdated: "2025-01-04",
        licensePlate: "GHI789",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: null,
        dailyUsage: 0,
        estMaintainance: null,
        address: {
            street: "789 Oak St",
            city: "Springfield",
            latitude: 38.89511,
            longitude: -77.03637
        },
    },
    {
        id: 4,
        model: "Chevrolet Cruze",
        driverId: 4,
        kilometers: 20000,
        lastUpdated: "2025-01-03",
        licensePlate: "JKL012",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: null,
        dailyUsage: 0,
        estMaintainance: null,
        address: {
            street: "101 Maple St",
            city: "Springfield",
            latitude: 38.89511,
            longitude: -77.03637
        },
    },
    {
        id: 5,
        model: "Seat Ibiza",
        driverId: 5,
        kilometers: 5000,
        lastUpdated: "2025-01-02",
        licensePlate: "MNO345",
        reminderSent: false,
        reminderSentDate: null,
        inMaintenance: false,
        lastMaintainance: null,
        dailyUsage: 0,
        estMaintainance: null,
        address: {
            street: "Carrer de sa Drassaneta",
            city: "Ibiza",
            latitude: 38.90883,
            longitude: 1.43296
        },
    },
    {
        id: 6,
        model: "Seat Leon",
        driverId: 6,
        kilometers: 10000,
        lastUpdated: "2025-01-01",
        licensePlate: "PQR678",
        reminderSent: false,
        reminderSentDate:
