name: Deploy a EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 🔑 Configurar SSH
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: 📡 Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/car-rental-backend
            git pull origin main
            sudo chmod -R 777 ./tmp/sessions
            # Build y start con Docker Compose
            docker-compose down
            docker-compose build
            docker-compose up -d
            docker system prune -af
          EOF
